apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-app 
  labels: 
    app: nginx-app
  spec:
    containers:
    - name: nginx-app 
      image: nginx
      imagePullPolicy: Always
      ports:
      - containerPort: 80 
      volumeMounts:
      - name: app-data
        mountPath: /usr/share/nginx/html
    volumes:
    - name: app-data
      persistentVolumeClaim:
        claimName: app-data-claim