apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
container:
  - name: nginx-pod
    image: nginx:1.14.0
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
volumes:
  - name: data
    #emptyDir: {}