apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-app 
  labels: 
    app: nginx-app
  spec:
    containers:
    - name: nginx-app 
      image: nginx
      imagePullPolicy: Always
      ports:
      - containerPort: 80 
      volumeMounts:
      - name: data
        mountPath: /usr/share/nginx/html
    volumes:
    - name: data
      persistentVolumeClaim:
        claimName: app-data-claim