apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi #Size of the volume
  accessModes:
    - ReadWriteOnce #type of access
  hostPath:
    path: "/data/app-data" #host location