apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ubuntu-ds
spec:
  selector:
    matchLabels:
      name: ubuntu
  template:
    metadata:
      labels:
        name: ubuntu
    spec:
      containers:
      - name: daemon-task
        image: ubuntu
        args:
        - /bin/bash
        - c
        - sleep 1000000