apiVersion: extentions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    nginx: nginx-dns
  name: nginx-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      task: two
  template:
    metadata:
      labels:
        task: two
    spec:
      containers:
      - name: nginx-dns
        image: nginx


---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-dns
spec:
  clusterIP: none
  type: ExternalName
  selector:
    nginx: nginx-dns