apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-test
  labels:
    nginx: rc
spec:
  replicas: 1
  selector:
    name: caglar
  template:
    metadata:
      labels:
        name: caglar
    spec:
      containers:
      - name: nginx-test
        image: nginx
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    nginx: rc
  ports:
  - protocol: TCP
    port: 80