
apiVersion: v1
kind: ReplicationController
metadata:
  labels: 
    rs: ngnix
  name: nginx-test
spec:
  replicas: 1
  selector:
    kube: task2
  template:
    metadata:
      labels:
        kube: task2
    spec: 
      containers:
      - name: nginx-test
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec: 
  selector:
    rs: nginx
  ports:
   - protocol: TCP
     port: 80
  type: NodePort