kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web-allow-dev
spec:
  podSelector:
    matchLabels:
      app:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          namespace: dev