apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  labels:
    run: frontend-pod
  name: frontend-pod
spec:
  nodeSelector:
    ssd: "true"
  containers:
  - image: centos
    name: centos
    stdin: true
    tty: true


---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: dev
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}

