apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  labels:
    run: java-pod
  name: java-pod
spec:
  nodeSelector:
    ssd: "true"
  containers:
  - image: centos
    env: test
    name: centos
    stdin: true
    tty: true




