apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kuard-pod-lp-rp-enabled
  name: kuard-pod-lp-rp-enabled
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1
    name: kuard
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 5                      # You don't have to use this line unless you need it.
      timeoutSeconds: 1                           # You don't have to use this line unless you need it.
      periodSeconds: 10                           # You don't have to use this line unless you need it.
      failureThreshold: 3                         # You don't have to use this line unless you need it.
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      periodSeconds: 2                            # You don't have to use this line unless you need it.
      initialDelaySeconds: 0                      # You don't have to use this line unless you need it.
      failureThreshold: 3                         # You don't have to use this line unless you need it.
      successThreshold: 1                         # You don't have to use this line unless you need it.
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
